[package]
name = "hello_world"
version = "0.1.0"
authors = ["Mathiris <mathias.gianotti97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
rust-crypto ="0.2.36"
rustc-serialize = "0.3.24"
